// ==Extension==
// @name         maxmovies-cc
// @version      v0.0.1
// @author       Auto-Discovery
// @lang         en
// @package      net.maxmovies-cc.ext
// @type         general
// @webSite      https://maxmovies.cc/
// @apiVersion   2
// @status       1
// ==/Extension==

/**
 * Auto-generated by discover.js.
 * Strategy: api_chain (confidence 0.85)
 * Review maxmovies-cc.log for what was found and what needs manual attention.
 */

var _debug = {
  generated: "2026-09-29T21:55:00.648Z",
  confidence: 0.85,
  missing: [],
  review_required: false,
  discovery_log: "maxmovies-cc.log"
};

var API_BASE = "https://maxmovies.cc/";

// ---- Detected API endpoints (JSON preferred over HTML scraping) ----
var API_SEARCH = "https://maxmovies.cc/api/search?q={{q}}&lang=en";
var API_DETAILS = null;
var API_SOURCES = null;

// ---- Detected selectors ----
// null means the discovery run could not detect this selector.
// search() throws a clear error rather than writing a placeholder.
var SEL = {
  container: null,
  title:     null,
  link:      null,
  poster:    null
};

// ---- Detected stream info ----
var STREAM = {
  type:   "unknown",
  url:    null,
  token:  null
};

// ---- Required HTTP headers ----
var HEADERS = {"Referer":"https://maxmovies.cc/"};

// ---- TV routing (for sites using /watch/id/season/episode) ----
var TV_MODE = false;

// ---- Replay recipe (preferred over a temporary direct stream URL) ----
var WATCH_RECIPE = {"version":1,"name":"watch-page-to-stream-chain","input_url":null,"steps":[{"id":"metadata","method":"GET","url":"{{input}}","headers":{"Referer":"https://maxmovies.cc/"},"body":null,"extract":{"videoSourceId":{"$regex":"videoSourceId(?:\\\\+|%22|\"|&quot;)*\\s*:\\s*(?:\\\\+|%22|\"|&quot;)*([a-zA-Z0-9_.-]+)"}}},{"id":"stream","method":"POST","url":"https://maxmovies.cc/api/stream","headers":{"Referer":"https://maxmovies.cc/","content-type":"application/json"},"body":{"videoSourceId":"{{steps.metadata.videoSourceId}}"},"extract":{"streamUrl":["hlsUrl","signedUrl"]}}],"result":{"url":"{{steps.stream.streamUrl}}"}};

function _failure(category, message) {
  try { console.warn("[" + category + "] " + message); } catch (e) {}
  return [];
}

function _streamType(url) {
  var pathname = String(url || "").split(/[?#]/, 1)[0].toLowerCase();
  try { pathname = new URL(_abs(url)).pathname.toLowerCase(); } catch (e) {}
  if (/\.m3u8$/.test(pathname)) return "hls";
  if (/\.mpd$/.test(pathname)) return "mpd";
  if (/\.mp4$/.test(pathname)) return "mp4";
  return "unknown";
}

function _source(url, type, headers) {
  var absolute = _abs(url);
  var source = String(absolute || "").split(/[?#]/, 1)[0];
  try { source = new URL(absolute).pathname; } catch (e) {}
  var out = { url: absolute, type: type || _streamType(absolute), source: source };
  if (headers && Object.keys(headers).length) out.headers = headers;
  return out;
}

function _runtimeEnv() {
  var env = {};
  try {
    if (typeof process !== "undefined" && process.env) env = process.env;
  } catch (e) {}
  return env;
}

function _resolve(value) {
  return _interpolate(value, { input: "", steps: {} }, _runtimeEnv());
}

function _abs(url) {
  if (!url) return url;
  var base = _resolve(API_BASE);
  try { return new URL(_resolve(url), base).href; } catch (e) { return _resolve(url); }
}

function _text(el) {
  return (el && el.textContent || "").trim();
}

function _mergeHeaders(extra) {
  var base = {};
  var k;
  for (k in HEADERS) base[k] = _resolve(HEADERS[k]);
  if (extra) { for (k in extra) base[k] = _resolve(extra[k]); }
  return base;
}

function _requireSelector(name, val) {
  if (!val) {
    throw new Error("Selector " + name + " was not detected. Manual configuration required.");
  }
}

function _interpolate(value, context, env) {
  if (typeof value === "string") {
    return value.replace(/\{\{([^}]+)\}\}/g, function (_, expression) {
      var key = expression.trim();
      var step;
      var current;
      var parts;
      var i;
      if (key === "input") return context.input == null ? "" : String(context.input);
      if (key === "q") return encodeURIComponent(context.q == null ? "" : context.q);
      if (key === "page") return encodeURIComponent(context.page == null ? "1" : context.page);
      if (key.indexOf("env.") === 0) return String(env[key.slice(4)] || "");
      if (key.indexOf("steps.") === 0) {
        parts = key.slice(6).split(".");
        step = context.steps[parts[0]] || {};
        current = step;
        for (i = 1; i < parts.length; i++) current = current == null ? undefined : current[parts[i]];
        return current == null ? "" : String(current);
      }
      return "";
    });
  }
  if (Array.isArray(value)) {
    return value.map(function (item) { return _interpolate(item, context, env); });
  }
  if (value && typeof value === "object") {
    var out = {};
    Object.keys(value).forEach(function (key) { out[key] = _interpolate(value[key], context, env); });
    return out;
  }
  return value;
}

async function _runRecipe(recipe, input) {
  var env = this && this.env ? this.env : _runtimeEnv();
  var context = { input: input, steps: {} };
  var i;
  var j;
  for (i = 0; i < recipe.steps.length; i++) {
    var step = _interpolate(recipe.steps[i], context, env);
    var init = { url: step.url, method: step.method, headers: _interpolate(_mergeHeaders(step.headers || {}), context, env) };
    if (step.body != null && step.method !== "GET" && step.method !== "HEAD") {
      init.body = typeof step.body === "string" ? step.body : JSON.stringify(step.body);
      if (!Object.keys(init.headers).some(function (key) { return key.toLowerCase() === "content-type"; })) {
        init.headers["Content-Type"] = "application/json";
      }
    }
    var response = await this.request(init);
    var parsed = response.body || "";
    try { parsed = JSON.parse(parsed); } catch (e) {}
    var extracted = {};
    var paths = step.extract || {};
    Object.keys(paths).forEach(function (name) {
      var candidates = Array.isArray(paths[name]) ? paths[name] : [paths[name]];
      for (var pathIndex = 0; pathIndex < candidates.length; pathIndex++) {
        if (candidates[pathIndex] && typeof candidates[pathIndex] === "object" && candidates[pathIndex].$regex) {
          var regexMatch = String(parsed).match(new RegExp(candidates[pathIndex].$regex));
          if (regexMatch) {
            extracted[name] = regexMatch[1] || regexMatch[0];
            return;
          }
          continue;
        }
        var current = parsed;
        String(candidates[pathIndex]).replace(/\[(\d+)\]/g, ".$1").split(".").filter(Boolean).forEach(function (part) {
          current = current == null ? undefined : current[part];
        });
        if (current != null) {
          extracted[name] = current;
          return;
        }
      }
    });
    context.steps[step.id] = extracted;
  }
  if (!recipe.result) throw new Error("Replay recipe has no result mapping.");
  return _interpolate(recipe.result, context, env);
}

// SPECTA compatibility shim.
//
// The upstream file targets a different contract: it exposes a global
// `watch(url)` and a global `search(kw, page)`, and nothing else. SPECTA calls
// `search`, `latest`, `details`, `getSources`, and `healthCheck` on the
// instance, so every one of those except `search` was missing and threw
// "This source does not implement ...". That is a node which installs cleanly,
// reports 100%, and can never reach playback.
//
// Method names below are exactly those the runtime invokes.
//
// It MUST extend SpectaExtension: that base class supplies `this.request(...)`,
// which reaches the network over the sandbox's `specta_request` channel. A bare
// class has no `request`, so every call failed, the provider caught it, and
// `search` returned [] — silently, with no error anywhere. That is exactly the
// "active node, 0 results" symptom.
class Extension extends SpectaExtension {
  // The upstream functions are plain globals that read `this.request`, so the
  // instance must be passed as the receiver. A bare `search(query, page)` call
  // would run with `this` undefined, `this.request` would throw, and the
  // provider's own catch would swallow it into an empty result.
  async search(query, page) { return await search.call(this, query, page); }
  async latest(page) { return await latest.call(this, page); }

  // The upstream site embeds its own title/poster on the watch page, so
  // details are read from there rather than from a second API.
  async details(reference) {
    const res = await this.request({
      url: reference, method: 'GET', headers: HEADERS,
    });
    const body = (res && res.body) || '';
    const title = (/<title[^>]*>([\s\S]*?)<\/title>/i.exec(body) || [])[1] || '';
    // The page embeds escaped JSON, and a poster URL may itself contain an
    // escaped code point (`\u0026` in a query string). A negated
    // `[^"\\]` class therefore stops at that backslash and the match fails.
    // Matching lazily up to the next escaped quote handles both forms.
    const poster = (/\\?"poster\\?"\s*:\s*\\?"(.*?)\\?"/s.exec(body) || [])[1] || '';
    const date = (/\\?"releaseDate\\?"\s*:\s*\\?"([^"\\]+)\\?"/.exec(body) || [])[1] || '';
    const year = date ? parseInt(date.slice(0, 4), 10) : null;
    // "Watch: Spider — MaxMovies" -> "Spider"
    const clean = title.replace(/^\s*watch:\s*/i, '').replace(/\s*[—–-]\s*maxmovies\s*$/i, '').trim();
    return {
      id: reference, title: clean,
      type: 'movie', cover: poster || null,
      year: isNaN(year) ? null : year, description: '', genres: [],
    };
  }

  // `watch` is the upstream name for "turn a reference into a playable URL".
  // SPECTA expects a LIST of sources; one recipe result is exactly one source.
  async getSources(reference) {
    const source = await watch.call(this, reference);
    return [{
      url: source.url, type: source.type || 'hls',
      quality: null, label: 'Auto',
      // The CDN checks Referer, so playback must present it.
      headers: Object.assign({}, source.headers || HEADERS),
    }];
  }

  async capabilities() {
    return {
      discovery: { search: true, latest: true },
      details: true, sources: true, network: true,
    };
  }

  async healthCheck() {
    try {
      const res = await this.request({
        url: 'https://maxmovies.cc/api/search?q=health&lang=en',
        method: 'GET', headers: HEADERS,
      });
      return res.status >= 200 && res.status < 300;
    } catch (e) {
      return false; // genuinely unreachable is unhealthy, unlike "no healthCheck"
    }
  }
}

async function latest(page) {
  return search("", page);
}

function _b64decode(str) {
  var chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=";
  var clean = String(str).replace(/[^A-Za-z0-9+/=]/g, "");
  var out = "";
  for (var i = 0; i < clean.length;) {
    var enc1 = chars.indexOf(clean.charAt(i++));
    var enc2 = chars.indexOf(clean.charAt(i++));
    var enc3 = chars.indexOf(clean.charAt(i++));
    var enc4 = chars.indexOf(clean.charAt(i++));
    out += String.fromCharCode((enc1 << 2) | (enc2 >> 4));
    if (enc3 !== 64 && enc3 !== -1) out += String.fromCharCode(((enc2 & 15) << 4) | (enc3 >> 2));
    if (enc4 !== 64 && enc4 !== -1) out += String.fromCharCode(((enc3 & 3) << 6) | enc4);
  }
  return out;
}

async function search(kw, page) {
  page = page || 1;

  // Prefer the detected JSON API when one was found.
  var apiFailure = null;
  if (API_SEARCH) {
    var searchContext = { input: "", steps: {}, q: kw, page: page || 1 };
    var apiURL = _interpolate(API_SEARCH, searchContext, _runtimeEnv());
    try {
      var res = await this.request({ url: apiURL, method: "GET", headers: _mergeHeaders() });
      if (!res || res.status < 200 || res.status >= 300) {
        var httpError = new Error("Search API returned HTTP " + (res && res.status || "unknown"));
        httpError.name = "HTTPError";
        throw httpError;
      }
      var data = JSON.parse(res.body || "[]");
      var lists = [];
      if (Array.isArray(data)) lists.push(data);
      if (Array.isArray(data.results)) lists.push(data.results);
      if (Array.isArray(data.data)) lists.push(data.data);
      if (Array.isArray(data.items)) lists.push(data.items);
      if (Array.isArray(data.movies)) lists.push(data.movies);
      if (Array.isArray(data.tv)) lists.push(data.tv);
      var out = [];
      for (var listIndex = 0; listIndex < lists.length; listIndex++) {
        var list = lists[listIndex];
        for (var i = 0; i < list.length; i++) {
          var item = list[i];
          var t = item.title || item.name || "";
          var l = item.url || item.link || item.slug || "";
          var kind = list === data.movies ? "movie" : (list === data.tv ? "tv" : "");
          if (!l && kind && item.id != null) l = "/watch/" + kind + "-" + String(item.id);
          var c = item.cover || item.poster || item.image || item.posterUrl || "";
          if (t && l) out.push({ title: t, url: _abs(l), cover: _abs(c) });
        }
      }
      if (out.length > 0) return out;
    } catch (e) {
      var category = "API_NETWORK_ERROR";
      if (e && (e.name === "AbortError" || /timeout/i.test(e.message || ""))) category = "API_TIMEOUT";
      else if (e && e.name === "HTTPError") category = "API_HTTP_ERROR";
      apiFailure = category;
      try { console.warn("[" + category + "] " + (e && e.message ? e.message : String(e))); } catch (logError) {}
      if (!SEL || !SEL.container || !SEL.title || !SEL.link) return [];
    }
  }

  // HTML scraping fallback.
  if (!SEL || !SEL.container) return _failure("DOM_SELECTOR_MISSING", "No DOM container selector is available.");
  if (!SEL.title || !SEL.link) return _failure("DOM_SELECTOR_MISSING", "DOM title or link selector is missing.");
  var url = API_BASE + "/search?q=" + encodeURIComponent(kw) + "&page=" + encodeURIComponent(page || 1);
  var r = await this.request({ url: url, method: "GET", headers: _mergeHeaders() });
  var $ = this.cheerio.load(r.body || "");
  var results = [];
  $(SEL.container).each(function (i, el) {
    var title = $(el).find(SEL.title).first();
    var link  = $(el).find(SEL.link).first();
    var poster = $(el).find(SEL.poster).first();
    var t = _text(title);
    var l = link.attr("href") || "";
    var c = poster.attr("data-src") || poster.attr("src") || "";
    if (t && l) {
      results.push({ title: t, url: _abs(l), cover: _abs(c) });
    }
  });
  if (results.length === 0) return _failure(apiFailure || "DOM_EXTRACTION_EMPTY", apiFailure ? "API failed and DOM fallback was empty." : "DOM selectors matched no usable results.");
  return results;
}

async function watch(url) {
  // Preferred path: execute the replay recipe to obtain a fresh URL.
  if (WATCH_RECIPE) {
    try {
      var replayed = await _runRecipe.call(this, WATCH_RECIPE, url);
      if (replayed && replayed.url) {
        return _source(replayed.url, replayed.type, _mergeHeaders());
      }
    } catch (e) {
      throw new Error("Replay recipe failed for " + url + ": " + e.message);
    }
  }

  // Direct URL fallback. This may expire if no replay recipe is available.
  if (STREAM.url) {
    return _source(STREAM.url, STREAM.type, _mergeHeaders());
  }

  // Template B: API chain replay.
  if (API_SOURCES) {
    try {
      var sres = await this.request({ url: _resolve(API_SOURCES), method: "GET", headers: _mergeHeaders() });
      var sdata = JSON.parse(sres.body || "{}");
      var surl = sdata.url || sdata.stream || sdata.file || "";
      if (surl) return _source(surl, _streamType(surl), _mergeHeaders());
    } catch (e) { /* API sources not available */ }
  }

  // Template C: fetch the page and look for embedded stream variables.
  var res = await this.request({ url: url, method: "GET", headers: _mergeHeaders() });
  var body = res.body || "";

  var m = body.match(/(?:file|source|videoUrl|src|stream_url)\s*[:=]\s*["']([^"']+?\.(?:m3u8|mp4|mpd))["']/i);
  if (m) return _source(m[1], _streamType(m[1]), _mergeHeaders());

  var b64 = body.match(/(?:file|source|videoUrl|src)\s*[:=]\s*["']([A-Za-z0-9+/_-]{20,}={0,2})["']/i);
  if (b64) {
    try {
      var decoded = _b64decode(b64[1]);
      if (decoded.indexOf("http") !== -1) {
        return _source(decoded, _streamType(decoded), _mergeHeaders());
      }
    } catch (e) { /* not valid base64 */ }
  }

  throw new Error("No stream URL detected for " + url + ". Manual extraction required.");
}
